In [1]:
import numpy as np


In [36]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype = float)
print(a, "\n\n", b, "\n\n", c)

[1 2 3] 

 [[1.5 2.  3. ]
 [4.  5.  6. ]] 

 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
np.arange(10,25,5)
np.linspace(0, 2, 9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [41]:
q = np.eye(4)
q

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.random.random((2,2))

array([[0.19585873, 0.27599765],
       [0.82005943, 0.93301734]])

### 数据类型
>>> np.int64 

>>> np.float32 

>>> np.complex 

>>> np.bool 

>>> np.object 

>>> np.string_

>>> np.unicode_

In [43]:
"""
支持的基本运算
—  四则运算
- e的幂，平方根，
- 正弦，余弦
- 自然对数d
- 点积
"""
np.exp(q)

array([[2.71828183, 1.        , 1.        , 1.        ],
       [1.        , 2.71828183, 1.        , 1.        ],
       [1.        , 1.        , 2.71828183, 1.        ],
       [1.        , 1.        , 1.        , 2.71828183]])

In [45]:
a

array([1, 2, 3])

In [58]:
"""
矩阵操作
- 转置
- 改变形状
- 合并数组
- 分割数组
"""
# 转置
i = np.transpose(b)
print(i, "\n\n", i.T,"\n\n")

# 改变形状
x = b.ravel()  # 拉平数组
y = b.reshape(6,1)
print(x, "\n", y)

print("-----")
# 添加或删除值
# h.resize((2,6)) 
# np.append(h,g) 
print(np.insert(a, 1, 5))
print(np.delete(a,[1]))

print("----")
print(np.concatenate((a,d),axis=0))  #  拼接
print(np.vstack((a,b)))


# 分割数组


[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]] 

 [[1.5 2.  3. ]
 [4.  5.  6. ]] 


[1.5 2.  3.  4.  5.  6. ] 
 [[1.5]
 [2. ]
 [3. ]
 [4. ]
 [5. ]
 [6. ]]
-----
[1 5 2 3]
[1 3]
----
[ 1  2  3 10 15 20]
[[1.  2.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]


In [ ]:
"""
对比
"""